# Generated by Django 5.2.14 on 2026-06-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='device_token',
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='auth',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='endpoint',
            field=models.URLField(blank=True, default='', max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='p256dh',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
