# Generated by Django 5.2.14 on 2026-06-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_devicetoken_device_token_devicetoken_auth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='giving_source',
            field=models.CharField(choices=[('online', 'online'), ('manual', 'manual')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='paybill_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
