# Generated by Django 5.2.14 on 2026-06-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emailverificationotp_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('ACTIVE', 'ACTIVE'), ('REJECTED', 'REJECTED')], default='PENDING_APPROVAL', max_length=50),
        ),
    ]
