# Generated by Django 5.2.14 on 2026-07-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_children_ministry_models'),
        ('api', '0010_department_admin_assignments'),
        ('api', '0011_department_admin_assignments'),
    ]

    operations = [
    ]
