# Generated by Django 5.2.14 on 2026-07-09 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20260702_0903'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='childattendancesession',
            new_name='api_childat_session_15f4ad_idx',
            old_name='api_childatt_session_idx',
        ),
        migrations.AlterField(
            model_name='childattendancerecord',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='childattendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('ACTIVE', 'ACTIVE'), ('REJECTED', 'REJECTED'), ('SUSPENDED', 'SUSPENDED')], default='PENDING_APPROVAL', max_length=50),
        ),
        migrations.AddIndex(
            model_name='childattendancerecord',
            index=models.Index(fields=['session', 'child'], name='api_childat_session_ec0066_idx'),
        ),
        migrations.AddConstraint(
            model_name='childattendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'child'), name='unique_session_child_attendance'),
        ),
    ]
