# Generated by Django 5.2.14 on 2026-07-09 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_memberprofile_suspended_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='api.ministry')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_attendance_marked_records', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.departmentattendancesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='departmentattendancesession',
            index=models.Index(fields=['ministry', 'session_date'], name='api_departm_ministr_1f578e_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentattendancerecord',
            index=models.Index(fields=['session', 'member'], name='api_departm_session_7b73e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentattendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'member'), name='unique_session_member_attendance'),
        ),
    ]
