# Generated by Django 5.2.14 on 2026-07-09 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_department_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.ministry'),
        ),
    ]
