# Generated by Django 5.2.14 on 2026-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='agreed_to_policies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='baptized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='church_branch',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='date_of_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='member_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='prayer_request',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='purpose_of_visit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='remember_me_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='residential_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='service_attended',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='visitor_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('PENDING_EMAIL_VERIFICATION', 'PENDING_EMAIL_VERIFICATION'), ('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('ACTIVE', 'ACTIVE'), ('REJECTED', 'REJECTED'), ('SUSPENDED', 'SUSPENDED'), ('DISABLED', 'DISABLED'), ('LOCKED', 'LOCKED')], default='PENDING_EMAIL_VERIFICATION', max_length=50),
        ),
    ]
