# Generated by Django 5.2.14 on 2026-07-10 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_expand_member_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaSTKPushRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Tithes', 'Tithes'), ('Offerings', 'Offerings'), ('Building Fund', 'Building Fund'), ('Missions', 'Missions'), ('Welfare Support', 'Welfare Support'), ('Special Projects', 'Special Projects')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('account_reference', models.CharField(blank=True, default='', max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, default='', max_length=100)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20)),
                ('result_code', models.CharField(blank=True, default='', max_length=10)),
                ('result_desc', models.TextField(blank=True, default='')),
                ('mpesa_receipt_number', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stk_push_request', to='api.donation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
