# Generated by Django 5.2.14 on 2026-07-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_mpesastkpushrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberhomecell',
            name='homecell',
            field=models.ForeignKey(limit_choices_to={'category': 'homecell'}, on_delete=django.db.models.deletion.PROTECT, to='api.ministry'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='category',
            field=models.CharField(choices=[('ministry', 'Ministry / Department'), ('homecell', 'Homecell')], default='ministry', max_length=20),
        ),
        migrations.DeleteModel(
            name='Homecell',
        ),
    ]
