# Generated by Django 5.2.14 on 2026-07-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_memberhomecell_homecell_ministry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='depositor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('Tithe', 'Tithe'), ('Offering', 'Offering'), ('Sacrifice', 'Sacrifice'), ('Thanksgiving', 'Thanksgiving'), ('Project', 'Project'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='giving_source',
            field=models.CharField(choices=[('online', 'online'), ('manual', 'manual'), ('c2b', 'c2b')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='mpesastkpushrequest',
            name='category',
            field=models.CharField(choices=[('Tithe', 'Tithe'), ('Offering', 'Offering'), ('Sacrifice', 'Sacrifice'), ('Thanksgiving', 'Thanksgiving'), ('Project', 'Project'), ('Others', 'Others')], max_length=50),
        ),
    ]
