# Generated by Django 5.2.14 on 2026-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_gallery_galleryitem_delete_galleryphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('sunday_service', 'Sunday Service'), ('event', 'Event'), ('conference', 'Conference'), ('crusade', 'Crusade'), ('seminar', 'Seminar'), ('camp', 'Camp'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
