# Generated by Django 5.2.14 on 2026-07-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_gallerycategory_gallery_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('ACTIVE', 'ACTIVE'), ('REJECTED', 'REJECTED'), ('SUSPENDED', 'SUSPENDED'), ('DISABLED', 'DISABLED'), ('LOCKED', 'LOCKED')], default='PENDING_APPROVAL', max_length=50),
        ),
        migrations.DeleteModel(
            name='EmailVerificationOTP',
        ),
    ]
