# Generated by Django 5.2.14 on 2026-07-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_memberprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='county',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='town_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
