# Generated by Django 5.2.14 on 2026-07-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_departmentadminassignment_assignment_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='leader',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
