# Generated by Django 5.2.14 on 2026-07-16 05:30

from django.db import migrations, models


def grandfather_existing_rows_as_approved(apps, schema_editor):
    # Every MemberMinistry row that already existed before this migration
    # was joined under the old no-approval system - the AddField above
    # would otherwise backfill them all as PENDING, incorrectly demoting
    # already-active ministry members. Only rows created after this point
    # (via the new join-request flow) should start PENDING.
    MemberMinistry = apps.get_model('api', 'MemberMinistry')
    MemberMinistry.objects.update(status='APPROVED')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_ministry_description_alter_ministry_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberministry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.RunPython(grandfather_existing_rows_as_approved, noop),
    ]
