# Generated by Django 5.2.14 on 2026-07-16 05:35

from django.db import migrations

# Corrects naming drift in the ministries seeded by seed_if_empty() (which
# only fires on an empty table, so an already-seeded system needs this data
# migration to catch up to the corrected homecells_defaults.MINISTRY_OPTIONS
# names). Exact old-name match only, so it's a no-op wherever an admin
# already renamed a row themselves.
RENAMES = {
    'Children Ministry': "Children's Ministry",
    'Church choir': 'Church Choir',
    'Development': 'Development Ministry',
    'Hospitality': 'Hospitality Ministry',
    'Protocol': 'Protocol Ministry',
    'Sanctuary Keeper': 'Sanctuary Keeper Ministry',
    'Ushering': 'Ushering Ministry',
    'WWK': "WWK (Women's Work)",
}


def rename_ministries(apps, schema_editor):
    Ministry = apps.get_model('api', 'Ministry')
    for old_name, new_name in RENAMES.items():
        Ministry.objects.filter(category='ministry', ministry_name=old_name).update(ministry_name=new_name)


def reverse_rename_ministries(apps, schema_editor):
    Ministry = apps.get_model('api', 'Ministry')
    for old_name, new_name in RENAMES.items():
        Ministry.objects.filter(category='ministry', ministry_name=new_name).update(ministry_name=old_name)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_memberministry_status'),
    ]

    operations = [
        migrations.RunPython(rename_ministries, reverse_rename_ministries),
    ]
