# Generated by Django 5.2.14 on 2026-07-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_seeded_ministries'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentadminassignment',
            name='duties',
            field=models.TextField(blank=True, default=''),
        ),
    ]
