# Generated by Django 5.2.14 on 2026-07-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_departmentadminassignment_duties'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/posters/'),
        ),
    ]
