# Generated by Django 5.2.14 on 2026-07-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_mediateammember_is_active_mediateammember_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Successful', max_length=20),
        ),
    ]
