# Generated by Django 5.2.14 on 2026-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='membership_upgrade_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='membership_upgrade_status',
            field=models.CharField(choices=[('NONE', 'NONE'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], default='NONE', max_length=10),
        ),
    ]
