# Generated by Django 5.2.14 on 2026-07-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_memberprofile_membership_upgrade_requested_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesastkpushrequest',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='mpesastkpushrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mpesastkpushrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='GivingCategory',
        ),
        migrations.DeleteModel(
            name='MpesaSTKPushRequest',
        ),
    ]
