# Generated by Django 5.2.14 on 2026-07-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_giving_payment_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='is_live',
        ),
    ]
