# Generated by Django 5.2.14 on 2026-07-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_livestream_remove_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='speaker',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
