# Generated by Django 5.2.14 on 2026-07-28 10:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_sermon_speaker_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='galleries/albums/covers/', validators=[api.models.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/posters/', validators=[api.models.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='galleries/covers/', validators=[api.models.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='galleries/items/', validators=[api.models.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='galleries/items/thumbnails/', validators=[api.models.validate_image_upload_size]),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[api.models.validate_image_upload_size]),
        ),
    ]
