# Generated by Django 5.2.14 on 2026-07-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_blacklisted_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='tokens_invalid_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
