# Generated by Django 5.2.14 on 2026-07-31 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_tokens_invalid_before'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('speaker', models.CharField(blank=True, default='', max_length=255)),
                ('theme', models.CharField(blank=True, default='', max_length=255)),
                ('scripture_reference', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_link', models.URLField()),
                ('meeting_platform', models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('built_in', 'Built-in Video Meeting')], default='google_meet', max_length=20)),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True, default='')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_online_meetings', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_meetings', to='api.ministry')),
            ],
            options={
                'ordering': ['-meeting_date', '-start_time'],
            },
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to='api.onlinemeeting'),
        ),
        migrations.CreateModel(
            name='OnlineMeetingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='online_meeting_attachments/')),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.onlinemeeting')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineMeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.onlinemeeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineMeetingPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='api.onlinemeeting')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineMeetingPollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.onlinemeetingpoll')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineMeetingPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.onlinemeetingpolloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.onlinemeetingpoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_meeting_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineMeetingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.onlinemeeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_meeting_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='onlinemeeting',
            index=models.Index(fields=['ministry', 'meeting_date'], name='api_onlinem_ministr_44b4d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='onlinemeetingattendance',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='unique_meeting_attendance'),
        ),
        migrations.AddConstraint(
            model_name='onlinemeetingpollvote',
            constraint=models.UniqueConstraint(fields=('poll', 'user'), name='unique_poll_vote_per_user'),
        ),
    ]
