# Generated by Django 5.2.14 on 2026-08-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_event_registration_user_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
